# Generated by Django 6.0.4 on 2026-04-29 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_region', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('variedad', models.CharField(blank=True, max_length=255, null=True)),
                ('calidad', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_comercio', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nombre', 'variedad', 'calidad'), name='unique_producto')],
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sub_sector', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.region')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mercado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mercado',
            constraint=models.UniqueConstraint(fields=('nombre', 'region'), name='unique_mercado'),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(fields=('fecha', 'producto', 'mercado'), name='unique_snapshot'),
        ),
    ]
