# Generated by Django 6.0.4 on 2026-05-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='unique_producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='calidad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='variedad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('nombre', 'variedad', 'calidad', 'origen'), name='unique_producto'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.unidad'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_comercio',
        ),
    ]
