# Generated by Django 6.0.4 on 2026-05-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_unidad_remove_producto_unique_producto_and_more'),
    ]

    operations = [
    ]
