# Generated by Django 6.0.4 on 2026-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_populate_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='tipo',
        ),
        migrations.AddField(
            model_name='unidad',
            name='cantidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
