# Generated by Django 6.0.4 on 2026-05-06 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_unidad_tipo_unidad_cantidad_unidad_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
