# Generated by Django 6.0.4 on 2026-05-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_unidad_created_at_unidad_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidad',
            old_name='nombre',
            new_name='nombre_original',
        ),
    ]
