# Generated by Django 6.0.4 on 2026-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_nombre_unidad_nombre_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nombre_original',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
